### ISSUE TITLE
Record.subscribe not triggered if result is empty

### ISSUE THREAD

**Issue by adamgoose** [hoxton-one/deepstream.io-client-js#11]
When I call `Record.subscribe(callback)`, it is not triggered if either of the following conditions are true:

1. The record did not previously existing
2. The record's value is an empty object.

These two conditions are probably identical, since a newly created record contains no data.

**Comment by yasserf** [comment]
Subscribe doesn't trigger immediately by default. Would it be possible that you're experiencing the following scenario?

```javascript
existingRecord = ds.record.getRecord( 'exists' );
 // Callback will be invoked as soon as the record's data load
existingRecord.subscribe( callback );

newRecord = ds.record.getRecord( 'new' );
 // Will only be invoked once the record changes
newRecord.subscribe( callback );

// Will always be invoked straight away
anyRecord.subscibe( callback, true ); 
```

**Comment by adamgoose** [comment]
Hm, it's possible. However, when inspecting the source, I deduced that the "immediate" is true by default. Am I trippin'?

**Comment by adamgoose** [comment]
Yes, I am... The docs say "optional = true", but I must have interpreted "default = true" by accident. My bad!
