### ISSUE TITLE
Cannot resolve module 'net'

### ISSUE THREAD

**Issue by bnwan** [hoxton-one/deepstream.io-client-js#12]
I'm getting this error when trying to bundle deepstream client using webpack

ERROR in ./~/deepstream.io-client-js/src/tcp/tcp-connection.js
Module not found: Error: Cannot resolve module 'net' in c:\_projects\bnwan\showmyphotos\node_modules\deepstream.io-client-js\src\tcp
 @ ./~/deepstream.io-client-js/src/tcp/tcp-connection.js 1:10-26

**Comment by bnwan** [comment]
I solved this by using webpack "resolve" to point the dist version of the client, instead of trying to bundle  it from source. The error comes up because webpack is unable to locate a browser (shimmed) version of the "net" nodejs module. This seems not to be an issue when using browserify. 

I'll have a look at this and create a pull request

**Comment by gothy** [comment]
Any ideas for fixing it the right way?
I've forced webpack to import the dist version too.
But now I'm getting this warning: ```Critical dependencies:
1:441-448 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/deepstream.io-client-js/dist/deepstream.js```

**Comment by jephir** [comment]
@gothy To silence the warning, add `deepstream.min.js` to Webpack's `module.noParse` option:

```js
module: {
		noParse: [
			/deepstream.min.js$/,
		],
  }
```

See http://webpack.github.io/docs/shimming-modules.html#configuration-option-module-noparse
