### ISSUE TITLE
RpcResponse.error() missing

### ISSUE THREAD

**Issue by iamveen** [hoxton-one/deepstream.io-client-js#14]
RpcResponse.error() is [documented](http://deepstream.io/docs/rpc_response.html), but doesn't appear to exist in [reality](https://github.com/hoxton-one/deepstream.io-client-js/blob/master/src/rpc/rpc-response.js).

**Comment by yasserf** [comment]
Many thanks for raising this issue, we are working on it now and it should be available in the next release.

**Comment by yasserf** [comment]
This has been fixed and released in 0.4.1
